package directorio_telefonico.vistas;

import directorio_telefonico.negocio.Cliente;
import directorio_telefonico.negocio.Directorio;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * ++
 *
 * @author Caro_Z
 */
public class AgregarCliente extends javax.swing.JInternalFrame {

    Directorio directorio;

    public AgregarCliente(Directorio directorio) {
        initComponents();
        this.directorio = directorio;
        this.setSize(600, 600);
        this.getContentPane().setBackground(new Color(51, 146, 103));

    }

    private void limpiar() {
        txtDni_agregarCliente.setText("");
        txtNombre_agregarCliente.setText("");
        txtApellido_agregarCliente.setText("");
        txtDireccion_agregarCliente.setText("");
        txtCiudad_agregarCliente.setText("");
        txtCiudad_agregarCliente.setText("");
        txtTelefono_agregarCliente.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDni_agregarCliente = new javax.swing.JTextField();
        txtNombre_agregarCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido_agregarCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion_agregarCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCiudad_agregarCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTelefono_agregarCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar_agregarCliente = new javax.swing.JButton();
        btnSalir_agregarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBtnNuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DNI");

        txtDni_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtDni_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDni_agregarClienteFocusLost(evt);
            }
        });
        txtDni_agregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDni_agregarClienteKeyTyped(evt);
            }
        });

        txtNombre_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombre_agregarClienteFocusLost(evt);
            }
        });
        txtNombre_agregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_agregarClienteKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");

        txtApellido_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtApellido_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellido_agregarClienteFocusLost(evt);
            }
        });
        txtApellido_agregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido_agregarClienteKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APELLIDO");

        txtDireccion_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtDireccion_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccion_agregarClienteFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DIRECCION");

        txtCiudad_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtCiudad_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCiudad_agregarClienteFocusLost(evt);
            }
        });
        txtCiudad_agregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudad_agregarClienteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CIUDAD");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtTelefono_agregarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefono_agregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefono_agregarClienteFocusLost(evt);
            }
        });
        txtTelefono_agregarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono_agregarClienteKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELEFONO");

        btnGuardar_agregarCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardar_agregarCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnGuardar_agregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar_agregarCliente.setText("GUARDAR");
        btnGuardar_agregarCliente.setEnabled(false);
        btnGuardar_agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_agregarClienteActionPerformed(evt);
            }
        });

        btnSalir_agregarCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir_agregarCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir_agregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir_agregarCliente.setText("SALIR");
        btnSalir_agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir_agregarClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AGREGAR   CLIENTE");

        jBtnNuevo.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jBtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNuevo.setText("NUEVO");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion_agregarCliente)
                            .addComponent(txtCiudad_agregarCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido_agregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtNombre_agregarCliente)
                            .addComponent(txtDni_agregarCliente))))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnGuardar_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(btnSalir_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(txtTelefono_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCiudad_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDni_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono_agregarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir_agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar_agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_agregarClienteActionPerformed

        Long dni = Long.parseLong(txtDni_agregarCliente.getText());
        String nom = txtNombre_agregarCliente.getText();
        String ape = txtApellido_agregarCliente.getText();
        String dir = txtDireccion_agregarCliente.getText();
        String ciu = txtCiudad_agregarCliente.getText();

        Cliente cli = new Cliente(dni, nom, ape, ciu, dir);

        Long tel = Long.parseLong(txtTelefono_agregarCliente.getText());

        boolean ex = MenuPrincipal.directorio.agregarCliente(tel, cli);
        if (!ex) {
            JOptionPane.showMessageDialog(this, "Este nro de telefono ya existe");

        } else {
            JOptionPane.showMessageDialog(this, " El cliente se ha guardado con éxito!");
        }

    }//GEN-LAST:event_btnGuardar_agregarClienteActionPerformed

    private void btnSalir_agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir_agregarClienteActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalir_agregarClienteActionPerformed

    private void txtDni_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDni_agregarClienteFocusLost
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_txtDni_agregarClienteFocusLost

    private void txtNombre_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre_agregarClienteFocusLost
        // TODO add your handling code here:
        if (txtNombre_agregarCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Éste campo debe estar completo");
            txtNombre_agregarCliente.requestFocus();
            
        }
    }//GEN-LAST:event_txtNombre_agregarClienteFocusLost

    private void txtApellido_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellido_agregarClienteFocusLost
        // TODO add your handling code here:
        if (txtApellido_agregarCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Éste campo debe estar completo");
            txtApellido_agregarCliente.requestFocus();
            
        }
    }//GEN-LAST:event_txtApellido_agregarClienteFocusLost

    private void txtDireccion_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccion_agregarClienteFocusLost
        // TODO add your handling code here:
        if (txtDireccion_agregarCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Éste campo debe estar completo");
            txtDireccion_agregarCliente.requestFocus();
            
        }
    }//GEN-LAST:event_txtDireccion_agregarClienteFocusLost

    private void txtCiudad_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudad_agregarClienteFocusLost
        // TODO add your handling code here:
        if (txtCiudad_agregarCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Éste campo debe estar completo");
            txtCiudad_agregarCliente.requestFocus();
            
        }
    }//GEN-LAST:event_txtCiudad_agregarClienteFocusLost

    private void txtTelefono_agregarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefono_agregarClienteFocusLost
        // TODO add your handling code here:
       
         if(!txtTelefono_agregarCliente.getText().isEmpty())
                 if(!txtDni_agregarCliente.getText().isEmpty())
                    if(!txtNombre_agregarCliente.getText().isEmpty())
                        if(!txtApellido_agregarCliente.getText().isEmpty())
                            if(!txtDireccion_agregarCliente.getText().isEmpty())
                                if(!txtCiudad_agregarCliente.getText().isEmpty())
                               {
                            btnGuardar_agregarCliente.setEnabled(true);
                        }
    }//GEN-LAST:event_txtTelefono_agregarClienteFocusLost

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:

        limpiar();
        btnGuardar_agregarCliente.setEnabled(false);


    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void txtDni_agregarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDni_agregarClienteKeyTyped
        // TODO add your handling code here:
        
        int key=evt.getKeyChar();
        boolean numeros=key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtDni_agregarClienteKeyTyped

    private void txtTelefono_agregarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono_agregarClienteKeyTyped
        // TODO add your handling code here:
        
         int key=evt.getKeyChar();
        boolean numeros=key>=48 && key <=57;
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefono_agregarClienteKeyTyped

    private void txtNombre_agregarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_agregarClienteKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNombre_agregarClienteKeyTyped

    private void txtApellido_agregarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido_agregarClienteKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtApellido_agregarClienteKeyTyped

    private void txtCiudad_agregarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudad_agregarClienteKeyTyped
        // TODO add your handling code here:
        
        
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtCiudad_agregarClienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar_agregarCliente;
    private javax.swing.JButton btnSalir_agregarCliente;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApellido_agregarCliente;
    private javax.swing.JTextField txtCiudad_agregarCliente;
    private javax.swing.JTextField txtDireccion_agregarCliente;
    private javax.swing.JTextField txtDni_agregarCliente;
    private javax.swing.JTextField txtNombre_agregarCliente;
    private javax.swing.JTextField txtTelefono_agregarCliente;
    // End of variables declaration//GEN-END:variables
}
